os:
  - linux
  - osx
sudo: false
language: cpp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - bc
    - g++-4.8
env:
  matrix:
  - TRAVIS_NODE_VERSION="0.10"
  - TRAVIS_NODE_VERSION="0.12"
  - TRAVIS_NODE_VERSION="4"
  - TRAVIS_NODE_VERSION="5"
  - TRAVIS_NODE_VERSION="6"
  - TRAVIS_NODE_VERSION="7"
  - TRAVIS_NODE_VERSION="8"
  - TRAVIS_NODE_VERSION="9"
  - TRAVIS_NODE_VERSION="10"
matrix:
  exclude:
    - os: osx
      env: TRAVIS_NODE_VERSION="0.12"
  include:
    - language: python
      python: 2.7
      dist: xenial  # required for Python >= 3.7
      sudo: true    # required for Python >= 3.7
      install: pip intall flake8
      script: flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
  - $CXX --version
  - if [[ $TRAVIS_NODE_VERSION == "0.8" ]]; then npm config set strict-ssl false; fi
  - if [[ $(echo "$TRAVIS_NODE_VERSION < 4" | bc -l) ]]; then npm install npm@2 && mv node_modules npm && npm/.bin/npm --version && npm/.bin/npm install; else npm --version && npm install; fi
  - node_modules/.bin/node-gyp rebuild --directory test
script: node_modules/.bin/tap --gc test/js/*-test.js
