language: node_js
env:
  - NODE_VERSION="0.6"
  - NODE_VERSION="0.8"
  - NODE_VERSION="0.10.27"
  - NODE_VERSION="0.10.28"
  - NODE_VERSION="0.10.29"
  - NODE_VERSION="0.10.30"
  - NODE_VERSION="0.11.13"
node_js:
  - "0.10"
notifications:
  email:
    - rod@vagg.org
before_install:
  - npm install npm
  - mv node_modules npm
  - npm/.bin/npm --version
  - npm/.bin/npm install
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - node --version
  - node_modules/.bin/node-gyp rebuild --directory test
install:
script: tap --gc test/js/*-test.js
